### ISSUE TITLE
Organisation de l’espace collaboratif du projet CHIC

### ISSUE THREAD

**Issue by nicolasdb** [chic-europecreative/chic-europecreative.github.io#1]
![image](https://user-images.githubusercontent.com/12049360/33030003-68bb9af6-ce1a-11e7-9f54-ea85ce5af3f7.png)

## Architecture générale
A concevoir en entonnoir, en trois temps :
1. Site institutionnel, http://www.chic-europecreative.eu/ : large, grand public, à but
informatif
2. Espace « Do it yourself » : avec les tutoriels et les contenus précisés pour exploitation des
contenus contributifs – créé à partir de github, mais avec une interface et une ergonomie
accessible à un public « non-geek »
3. Espace contributif – sur github, pour ceux qui veulent apporter du contenu. 
Nécessite les tuto adhoc github. 

### TODO - Travailler les liens entre les 3 espaces :
- [ ] Trouver le bon renvoi de l’institutionnel vers le DIY  @Philippe
- [ ] Bien rédiger le lien du DIY vers le contributif, pour favoriser les « passages à l’acte » @Philippe

## Espace contributif
A réorganiser selon le modèle suivant :
- [x] Créer un espace github distinct de celui de l’Open Fab 
- [x] Créer 4 « repositories » (=dossiers)  
   - Chic 2.0 : toutes les données liées au projet Europe Creative en lui-même
       - Le dossier de présentation du projet (éventuellement, ajouter celui de Chic 1.0)
       - La documentation liée aux workshops et aux événements
       - Pistes de réflexion à creuser pour la suite
  - Pantolino : toutes les données (tuto notamment) liées à l’outil
  - Pedagogic content : tout ce qui a trait aux mallettes pédagogiques
  - chic-europecreative.github.io : les données de l’espace DIY

### TODO
- [x] Nicolas se charge de créer ces divers dossiers et @nicolasdb
- [x] d’y ranger les informations.  @nicolasdb
- [ ] Un référent par partenaire est à identifier pour formation à github + animation de la contribution à
échelle locale.

## Espace DIY
- [x] A créer en profitant d’une fonctionnalité github, qui permet de créer un site lisible et ergonomique
pour public non-averti, et faciliter l’accès aux productions CHIC.
### 4 pages
- Home
- About : rappeler le cadre général du projet CHIC
- Categories (titre à trouver) : reprend les 3 repositories CHIC 2.0 / Pantolino / pedagogic content
- How to contribute

- [x] Philippe se familiarise avec le fonctionnement de github, 
- [x] rédige la page How to contribute, prendre exemple sur https://opensource.guide/
- [ ] et travaille avec Nicolas pour rendre cet espace cohérent fond+forme.

## Divers
- [x] Présenter cela le 24/11 lors de la réunion partenaires
- [ ] Identifier des référents « contributifs » pour chaque partenaire volontaire
- [ ] Prévoir de recueillir des témoignages d’utilisateurs, notamment lors des foires des savoir-faire dans l’optique de faciliter le passage à l’acte contributif
